sudo: false

# get perlbrew environment
language: perl

# install only the required submodules
git:
  submodules: false
  
addons:
  apt:
    packages:
      valgrind

perl:
  - "5.24"
  - "5.20"
  
install:
  - cpanm Test::Files

env:
  - VALGRIND=
  - VALGRIND=--valgrind

script:
  - ./make.pl submodules
  - ./make.pl
  - ./make.pl check $VALGRIND

notifications:
  email:
    on_success: never
    on_failure: never