sudo: false

# get perlbrew environment
language: perl

# install only the required submodules
git:
  submodules: false
  
addons:
  apt:
    packages:
      valgrind

matrix:
  include:
    # Setting --debug make compilation faster
    - perl: "5.24"
      env: DEBUG=--debug
    - perl: "5.24"
    - perl: "5.20"
    - perl: "5.24"
      env:
        - VALGRIND=--valgrind
        - DEBUG=--debug
    
install:
  - cpanm File::Slurper
  - cpanm Text::Diff

script:
  - ./make.pl submodules
  - ./make.pl $DEBUG --verbose
  - ./make.pl check $VALGRIND

notifications:
  email:
    on_success: never
    on_failure: never