sudo: false

# get perlbrew environment
language: perl

# install only the required submodules
git:
  submodules: false
  
addons:
  apt:
    packages:
      valgrind

matrix:
  include:
    - perl: "5.24"
      env: VALGRIND=
    - perl: "5.20"
      env: VALGRIND=
    - perl: "5.24"
      env: VALGRIND=--valgrind
    
install:
  - cpanm File::Slurper
  - cpanm Text::Diff

script:
  - ./make.pl submodules
  - ./make.pl
  - ./make.pl check $VALGRIND

notifications:
  email:
    on_success: never
    on_failure: never