=pod

=head1 Contributing to pdfout's documentation

The documentation is maintained as L<Pod|https://metacpan.org/pod/distribution/perl/pod/perlpod.pod>
in the F<doc/> subdirectory.

L<Building the documentation|make#doc> is performed by F<make.pl>.

=head2 The TOC

The L<table of contents|index> of the documentation is maintained in F<doc/index.pod>.

=head2 Links

For internal links we use the following mechanism:

 L<Description|file-name>

, where C<file-name> does not have a '.html' or '.pod' suffix.


To link to a subheading, use

 L<Description|file-name#name of subheading>

Linking to a subheading in the current file is done with

 L<Description|#name of subheading>

