=head1 pdfout

Yet another PDF analysis and manipulation toolkit. pdfout is a command-line
front-end to L<mupdf|http://www.mupdf.com>, a fast library supporting PDF
parsing, rendering , creation and manipulation.

=head2 General information

=over

=item * L<Installation and testing|make>

=back

=head2 Extraction and Manipulation commands

=over


=item * L<The information dictionary|info>

=back

=head2 Internals

=over

=item * L<Manual internals|internal-docs>

=item * L<Metadata getters and setters|internal-get_set>

=item * L<The pdfout_data type|internal-data-formats>

=item * L<Character set conversion|internal-charset-conversion>

=item * L<Creation of blank PDFs|internal-create-pdf>

=item * L<Miscellaneous helper functions|internal-misc>

=back

=head2 MuPDF API

=head3 Fitz

=over

=item * L<Buffers and streams|mupdf-buffer-stream-output>

=item * L<Memory allocators|mupdf-allocators>

=back

=head3 PDF

=over

=item * L<PDF document|mupdf-pdf-document>

=item * L<PDF objects|mupdf-objects>

=item * L<The xref table: adding, removing and replacing indirect objects|mupdf-xref>

=back